### ISSUE TITLE
A segmentation fault for a valid plan

### ISSUE THREAD

**Issue by mabdula** [KCL-Planning/VAL#28] opened 2018-06-03 16:12 UTC
A segmentation fault happens when running domain, instance and plan which are in the attached zip file.
[bug1.zip](https://github.com/KCL-Planning/VAL/files/2066126/bug1.zip)

Cheers
Mohammad

**Comment by DerekLong101** [comment] 2018-06-05 12:03
This is a problem in the initial state - a better response would be for VAL to identify the syntax error! The problem is the use of (and ...) in the initial state, which is invalid syntax.

________________________________

**Comment by DerekLong101** [comment] 2019-08-08 09:57
I am closing this, since it is a syntax error in the spec. The improvement of reporting of errors is work in progress, but this issue is itself no longer relevant.

**Closed by DerekLong101** 2019-08-08 09:57 UTC
